name: Frontend CI

on:
  push:
    branches:
      - main
      - componentsManagement
    paths:
      - "frontEnd/**"
      - ".github/workflows/frontEnd-ci.yaml"
  pull_request:
    branches:
      - main
      - componentsManagement
    paths:
      - "frontEnd/**"
      - ".github/workflows/frontEnd-ci.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./frontEnd/package-lock.json"

      # Une seule étape d'installation avec l'option pour ignorer Husky
      - name: Install dependencies
        run: npm ci --ignore-scripts
        working-directory: ./frontEnd

      - name: Lint
        run: npm run lint
        working-directory: ./frontEnd
        continue-on-error: true

      # Mise à jour de la commande de test pour éviter les erreurs d'arguments
      - name: Run Tests
        run: npm test -- --watch=false --browser=chromium --headless
        working-directory: ./frontEnd

      - name: Production Build
        run: npm run build
        working-directory: ./frontEnd
